
import vazirFont from "@/constants/localFont";
import "../styles/globals.css";
import Header from "@/components/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
        <Header />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
